# Generated by Django 3.0.4 on 2020-03-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('directory', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='voice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument', models.CharField(choices=[('Piano', 'Piano'), ('Vocals', 'Vocals'), ('Bass', 'Bass'), ('Drums', 'Drums')], max_length=50)),
                ('isolated_voice_directory', models.CharField(max_length=255, null=True)),
                ('voice_sheet_directory', models.CharField(max_length=255, null=True)),
                ('voice_midi_directory', models.CharField(max_length=255, null=True)),
                ('voice_midi_audio_directory', models.CharField(max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
