# Generated by Django 3.0.4 on 2020-05-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200323_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_abc_directory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
